//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: withyoursquad/v2/auth.proto

package withyoursquad.v2;

@kotlin.jvm.JvmName("-initializecreateSessionRequest")
public inline fun createSessionRequest(block: withyoursquad.v2.CreateSessionRequestKt.Dsl.() -> kotlin.Unit): withyoursquad.v2.Auth.CreateSessionRequest =
  withyoursquad.v2.CreateSessionRequestKt.Dsl._create(withyoursquad.v2.Auth.CreateSessionRequest.newBuilder()).apply { block() }._build()
public object CreateSessionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: withyoursquad.v2.Auth.CreateSessionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: withyoursquad.v2.Auth.CreateSessionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): withyoursquad.v2.Auth.CreateSessionRequest = _builder.build()

    /**
     * <pre>
     * Phone number for phone-based verification
     * </pre>
     *
     * <code>optional string phone = 1;</code>
     */
    public var phone: kotlin.String
      @JvmName("getPhone")
      get() = _builder.getPhone()
      @JvmName("setPhone")
      set(value) {
        _builder.setPhone(value)
      }
    /**
     * <pre>
     * Phone number for phone-based verification
     * </pre>
     *
     * <code>optional string phone = 1;</code>
     */
    public fun clearPhone() {
      _builder.clearPhone()
    }
    /**
     * <pre>
     * Phone number for phone-based verification
     * </pre>
     *
     * <code>optional string phone = 1;</code>
     * @return Whether the phone field is set.
     */
    public fun hasPhone(): kotlin.Boolean {
      return _builder.hasPhone()
    }

    /**
     * <pre>
     * Verification code
     * </pre>
     *
     * <code>optional string code = 2;</code>
     */
    public var code: kotlin.String
      @JvmName("getCode")
      get() = _builder.getCode()
      @JvmName("setCode")
      set(value) {
        _builder.setCode(value)
      }
    /**
     * <pre>
     * Verification code
     * </pre>
     *
     * <code>optional string code = 2;</code>
     */
    public fun clearCode() {
      _builder.clearCode()
    }
    /**
     * <pre>
     * Verification code
     * </pre>
     *
     * <code>optional string code = 2;</code>
     * @return Whether the code field is set.
     */
    public fun hasCode(): kotlin.Boolean {
      return _builder.hasCode()
    }

    /**
     * <pre>
     * Email for email-based verification
     * </pre>
     *
     * <code>optional string email = 3;</code>
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * <pre>
     * Email for email-based verification
     * </pre>
     *
     * <code>optional string email = 3;</code>
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }
    /**
     * <pre>
     * Email for email-based verification
     * </pre>
     *
     * <code>optional string email = 3;</code>
     * @return Whether the email field is set.
     */
    public fun hasEmail(): kotlin.Boolean {
      return _builder.hasEmail()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun withyoursquad.v2.Auth.CreateSessionRequest.copy(block: withyoursquad.v2.CreateSessionRequestKt.Dsl.() -> kotlin.Unit): withyoursquad.v2.Auth.CreateSessionRequest =
  withyoursquad.v2.CreateSessionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

