//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: withyoursquad/v2/auth.proto

package withyoursquad.v2;

@kotlin.jvm.JvmName("-initializecreateSessionResponse")
public inline fun createSessionResponse(block: withyoursquad.v2.CreateSessionResponseKt.Dsl.() -> kotlin.Unit): withyoursquad.v2.Auth.CreateSessionResponse =
  withyoursquad.v2.CreateSessionResponseKt.Dsl._create(withyoursquad.v2.Auth.CreateSessionResponse.newBuilder()).apply { block() }._build()
public object CreateSessionResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: withyoursquad.v2.Auth.CreateSessionResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: withyoursquad.v2.Auth.CreateSessionResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): withyoursquad.v2.Auth.CreateSessionResponse = _builder.build()

    /**
     * <pre>
     * Status of session request
     * </pre>
     *
     * <code>.withyoursquad.v2.CreateSessionStatus status = 2;</code>
     */
    public var status: withyoursquad.v2.Auth.CreateSessionStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <pre>
     * Status of session request
     * </pre>
     *
     * <code>.withyoursquad.v2.CreateSessionStatus status = 2;</code>
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * <pre>
     * Access token for active sessions
     * </pre>
     *
     * <code>optional string access_token = 3;</code>
     */
    public var accessToken: kotlin.String
      @JvmName("getAccessToken")
      get() = _builder.getAccessToken()
      @JvmName("setAccessToken")
      set(value) {
        _builder.setAccessToken(value)
      }
    /**
     * <pre>
     * Access token for active sessions
     * </pre>
     *
     * <code>optional string access_token = 3;</code>
     */
    public fun clearAccessToken() {
      _builder.clearAccessToken()
    }
    /**
     * <pre>
     * Access token for active sessions
     * </pre>
     *
     * <code>optional string access_token = 3;</code>
     * @return Whether the accessToken field is set.
     */
    public fun hasAccessToken(): kotlin.Boolean {
      return _builder.hasAccessToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun withyoursquad.v2.Auth.CreateSessionResponse.copy(block: withyoursquad.v2.CreateSessionResponseKt.Dsl.() -> kotlin.Unit): withyoursquad.v2.Auth.CreateSessionResponse =
  withyoursquad.v2.CreateSessionResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

