//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: withyoursquad/v2/auth.proto

package withyoursquad.v2;

@kotlin.jvm.JvmName("-initializepartnerSyncResponse")
public inline fun partnerSyncResponse(block: withyoursquad.v2.PartnerSyncResponseKt.Dsl.() -> kotlin.Unit): withyoursquad.v2.Auth.PartnerSyncResponse =
  withyoursquad.v2.PartnerSyncResponseKt.Dsl._create(withyoursquad.v2.Auth.PartnerSyncResponse.newBuilder()).apply { block() }._build()
public object PartnerSyncResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: withyoursquad.v2.Auth.PartnerSyncResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: withyoursquad.v2.Auth.PartnerSyncResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): withyoursquad.v2.Auth.PartnerSyncResponse = _builder.build()

    /**
     * <code>string access_token = 1;</code>
     */
    public var accessToken: kotlin.String
      @JvmName("getAccessToken")
      get() = _builder.getAccessToken()
      @JvmName("setAccessToken")
      set(value) {
        _builder.setAccessToken(value)
      }
    /**
     * <code>string access_token = 1;</code>
     */
    public fun clearAccessToken() {
      _builder.clearAccessToken()
    }

    /**
     * <code>string user_id = 2;</code>
     */
    public var userId: kotlin.String
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>string user_id = 2;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * <code>bool is_new_user = 3;</code>
     */
    public var isNewUser: kotlin.Boolean
      @JvmName("getIsNewUser")
      get() = _builder.getIsNewUser()
      @JvmName("setIsNewUser")
      set(value) {
        _builder.setIsNewUser(value)
      }
    /**
     * <code>bool is_new_user = 3;</code>
     */
    public fun clearIsNewUser() {
      _builder.clearIsNewUser()
    }

    /**
     * <code>optional string display_name = 4;</code>
     */
    public var displayName: kotlin.String
      @JvmName("getDisplayName")
      get() = _builder.getDisplayName()
      @JvmName("setDisplayName")
      set(value) {
        _builder.setDisplayName(value)
      }
    /**
     * <code>optional string display_name = 4;</code>
     */
    public fun clearDisplayName() {
      _builder.clearDisplayName()
    }
    /**
     * <code>optional string display_name = 4;</code>
     * @return Whether the displayName field is set.
     */
    public fun hasDisplayName(): kotlin.Boolean {
      return _builder.hasDisplayName()
    }

    /**
     * <code>optional string community = 5;</code>
     */
    public var community: kotlin.String
      @JvmName("getCommunity")
      get() = _builder.getCommunity()
      @JvmName("setCommunity")
      set(value) {
        _builder.setCommunity(value)
      }
    /**
     * <code>optional string community = 5;</code>
     */
    public fun clearCommunity() {
      _builder.clearCommunity()
    }
    /**
     * <code>optional string community = 5;</code>
     * @return Whether the community field is set.
     */
    public fun hasCommunity(): kotlin.Boolean {
      return _builder.hasCommunity()
    }

    /**
     * <code>optional string email = 6;</code>
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * <code>optional string email = 6;</code>
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }
    /**
     * <code>optional string email = 6;</code>
     * @return Whether the email field is set.
     */
    public fun hasEmail(): kotlin.Boolean {
      return _builder.hasEmail()
    }

    /**
     * <code>optional string status = 7;</code>
     */
    public var status: kotlin.String
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>optional string status = 7;</code>
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
    /**
     * <code>optional string status = 7;</code>
     * @return Whether the status field is set.
     */
    public fun hasStatus(): kotlin.Boolean {
      return _builder.hasStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun withyoursquad.v2.Auth.PartnerSyncResponse.copy(block: withyoursquad.v2.PartnerSyncResponseKt.Dsl.() -> kotlin.Unit): withyoursquad.v2.Auth.PartnerSyncResponse =
  withyoursquad.v2.PartnerSyncResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

