//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: withyoursquad/v2/auth.proto

package withyoursquad.v2;

@kotlin.jvm.JvmName("-initializepartnerSyncRequest")
public inline fun partnerSyncRequest(block: withyoursquad.v2.PartnerSyncRequestKt.Dsl.() -> kotlin.Unit): withyoursquad.v2.Auth.PartnerSyncRequest =
  withyoursquad.v2.PartnerSyncRequestKt.Dsl._create(withyoursquad.v2.Auth.PartnerSyncRequest.newBuilder()).apply { block() }._build()
public object PartnerSyncRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: withyoursquad.v2.Auth.PartnerSyncRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: withyoursquad.v2.Auth.PartnerSyncRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): withyoursquad.v2.Auth.PartnerSyncRequest = _builder.build()

    /**
     * <pre>
     * Partner identifier (must match API key)
     * </pre>
     *
     * <code>string partner_id = 1;</code>
     */
    public var partnerId: kotlin.String
      @JvmName("getPartnerId")
      get() = _builder.getPartnerId()
      @JvmName("setPartnerId")
      set(value) {
        _builder.setPartnerId(value)
      }
    /**
     * <pre>
     * Partner identifier (must match API key)
     * </pre>
     *
     * <code>string partner_id = 1;</code>
     */
    public fun clearPartnerId() {
      _builder.clearPartnerId()
    }

    /**
     * <pre>
     * Community to scope the user to
     * </pre>
     *
     * <code>string community_id = 2;</code>
     */
    public var communityId: kotlin.String
      @JvmName("getCommunityId")
      get() = _builder.getCommunityId()
      @JvmName("setCommunityId")
      set(value) {
        _builder.setCommunityId(value)
      }
    /**
     * <pre>
     * Community to scope the user to
     * </pre>
     *
     * <code>string community_id = 2;</code>
     */
    public fun clearCommunityId() {
      _builder.clearCommunityId()
    }

    /**
     * <code>optional string email = 3;</code>
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * <code>optional string email = 3;</code>
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }
    /**
     * <code>optional string email = 3;</code>
     * @return Whether the email field is set.
     */
    public fun hasEmail(): kotlin.Boolean {
      return _builder.hasEmail()
    }

    /**
     * <code>optional string phone = 4;</code>
     */
    public var phone: kotlin.String
      @JvmName("getPhone")
      get() = _builder.getPhone()
      @JvmName("setPhone")
      set(value) {
        _builder.setPhone(value)
      }
    /**
     * <code>optional string phone = 4;</code>
     */
    public fun clearPhone() {
      _builder.clearPhone()
    }
    /**
     * <code>optional string phone = 4;</code>
     * @return Whether the phone field is set.
     */
    public fun hasPhone(): kotlin.Boolean {
      return _builder.hasPhone()
    }

    /**
     * <code>optional string display_name = 5;</code>
     */
    public var displayName: kotlin.String
      @JvmName("getDisplayName")
      get() = _builder.getDisplayName()
      @JvmName("setDisplayName")
      set(value) {
        _builder.setDisplayName(value)
      }
    /**
     * <code>optional string display_name = 5;</code>
     */
    public fun clearDisplayName() {
      _builder.clearDisplayName()
    }
    /**
     * <code>optional string display_name = 5;</code>
     * @return Whether the displayName field is set.
     */
    public fun hasDisplayName(): kotlin.Boolean {
      return _builder.hasDisplayName()
    }

    /**
     * <code>optional string avatar_url = 6;</code>
     */
    public var avatarUrl: kotlin.String
      @JvmName("getAvatarUrl")
      get() = _builder.getAvatarUrl()
      @JvmName("setAvatarUrl")
      set(value) {
        _builder.setAvatarUrl(value)
      }
    /**
     * <code>optional string avatar_url = 6;</code>
     */
    public fun clearAvatarUrl() {
      _builder.clearAvatarUrl()
    }
    /**
     * <code>optional string avatar_url = 6;</code>
     * @return Whether the avatarUrl field is set.
     */
    public fun hasAvatarUrl(): kotlin.Boolean {
      return _builder.hasAvatarUrl()
    }

    /**
     * <pre>
     * Host app's user ID for idempotent matching
     * </pre>
     *
     * <code>optional string external_user_id = 7;</code>
     */
    public var externalUserId: kotlin.String
      @JvmName("getExternalUserId")
      get() = _builder.getExternalUserId()
      @JvmName("setExternalUserId")
      set(value) {
        _builder.setExternalUserId(value)
      }
    /**
     * <pre>
     * Host app's user ID for idempotent matching
     * </pre>
     *
     * <code>optional string external_user_id = 7;</code>
     */
    public fun clearExternalUserId() {
      _builder.clearExternalUserId()
    }
    /**
     * <pre>
     * Host app's user ID for idempotent matching
     * </pre>
     *
     * <code>optional string external_user_id = 7;</code>
     * @return Whether the externalUserId field is set.
     */
    public fun hasExternalUserId(): kotlin.Boolean {
      return _builder.hasExternalUserId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun withyoursquad.v2.Auth.PartnerSyncRequest.copy(block: withyoursquad.v2.PartnerSyncRequestKt.Dsl.() -> kotlin.Unit): withyoursquad.v2.Auth.PartnerSyncRequest =
  withyoursquad.v2.PartnerSyncRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

